### ISSUE TITLE
Windows 10 compatibility

### ISSUE THREAD

**Issue by jdhitsolutions** [jdhitsolutions/StickyNotes#2]
The Sticky Notes application appears to now be a modern app on Windows 10. The stikynot.exe file from C:\Windows\System32 is now gone.

**Comment by jdhitsolutions** [comment]
I don't think this module will work with Windows 10. Testing with 10.0.14388.0 and StickyNotes is now a modern app. I can use Get-AppX to identify it and launch it. But the running app has no window title and cannot be selected with the legacy AppActivate() method. I can't find anyway to select the app to give it focus.

**Comment by mcharo** [comment]
Does this vary by edition of Windows 10?  On Home, I've got C:\Windows\System32\StikyNot.exe.  Or a change in a later build (my build is older than the one you tested on)?

**Comment by jdhitsolutions** [comment]
I think edition does matter. I'm running Windows 10 Pro and do not have the command line tool, only the modern app. And that app doesn't behave the same way with regard to keyboard shortcuts.
